server:
  port: 8081
      
 
spring:

  application:
    name: User

  datasource:
    url: jdbc:postgresql://localhost:5432/ms-user
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false

  rabbitmq:
    addresses:
    - amqps://xvlkeyxz:hCtWYvd5PTLeyDlteP3TR45CxpJetvkG@gull.rmq.cloudamqp.com/xvlkeyxz

broker:
  queue:
    email:
      name: default.email

